swagger: "2.0"
info:
  version: "0.0.1"
  title: Note App
  description: Save & View Text Notes
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - text/plain
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /notes:
    # binds a127 app logic to a route
    x-swagger-router-controller: notes
    get:
      description: Returns a list of saved notes
      # used as the method name of the controller
      operationId: getNotes
      responses:
        "200":
          description: Get all Notes
          schema:
            $ref: "#/definitions/AllNotes"
    post:
      operationId: saveNote
      parameters:
      - name: note
        in: body
        description: Text note you want to save
        schema:
          $ref: "#/definitions/Note"
      responses:
        "201":
          description: returns the saved note
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Note:
    type: string
  AllNotes:
    type: string
